sonar.projectKey=orderflow
sonar.projectName=OrderFlow
sonar.sources=app
sonar.tests=tests
sonar.test.inclusions=tests/**/*.py
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=tests/**
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300